#[cpu]
#name = "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz"
#curve = [171.2,0.0354,36.89,-10.13]
[cpu]
name = "Apple M4 Pro"
curve = [30.508760345993128,0.0730308567638932,20.451103066868207,-5.08379885619235]


#"event-statistics-java21" "fights-kafka" "rest-narration-java21" "apicurio", "apicurio", "ui-super-heroes"
[[process]]
name = "fights-rust"
up = "docker compose up --force-recreate -d"
down = "docker compose down"
redirect.to = "file"
process.type = "docker"
process.containers = ["fights-db", "heroes-db", "villains-db", "locations-db", "rest-fights", "rest-heroes", "rest-villains", "grpc-locations", "fights-db"]
startup_grace = "20s"

[[scenario]]
name = "k6-rust-high"
desc = "High test for 60s"
command = "k6 run high.js"
iterations = 3
processes = ["fights-rust"]

[[scenario]]
name = "k6-rust-low"
desc = "Low load test."
command = "k6 run low.js"
iterations = 3
processes = ["fights-rust"]

[[scenario]]
name = "k6-rust-none"
desc = "No load test."
command = "k6 run none.js"
iterations = 3
processes = ["fights-rust"]

[[scenario]]
name = "k6-rust-max"
desc = "No load test."
command = "k6 run max.js"
iterations = 3
processes = ["fights-rust"]


[[observation]]
name = "rust"
scenarios = ["k6-rust-low","k6-rust-high","k6-rust-none"]

[[observation]]
name = "rust-max"
scenarios = ["k6-rust-max"]
