services:
  k6:
    build: k6-image
    environment:
      K6_HOST: http://rest-fights:8000 
    command: ["bash", "-c", "while true; do sleep 3600; done"]
    volumes:
      - ./k6:/k6:ro
      - ./k6/results:/results
  rest-heroes:
    build: services/rest-heroes
    ports:
      - "8080:8000"
  rest-villains:
    build: services/rest-villains
    ports:
      - "8081:8000"
  grpc-locations:
    build: services/grpc-locations
    ports:
      - "50051:50051"
  rest-fights:
    build: services/rest-fights
    environment:
      HEROES_BASE_URL: http://rest-heroes:8000
      VILLAINS_BASE_URL: http://rest-villains:8000
      LOCATIONS_BASE_URL: http://grpc-locations:50051
    ports:
      - "8082:8000"
