services:
  fights-db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fights
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: super
    volumes:
      - ./database/fights-db/initialize-database.js:/docker-entrypoint-initdb.d/1-init-db.js
  rest-heroes:
    image: flyaruu/superheroes-rust-rest-heroes:latest
    depends_on:
      heroes-db:
        condition: service_healthy
    ports:
      - "8080:8000"
  rest-villains:
    image: flyaruu/superheroes-rust-rest-villains:latest
    depends_on:
      villains-db:
        condition: service_healthy
    ports:
      - "8081:8000"
  grpc-locations:
    image: flyaruu/superheroes-rust-grpc-locations:latest
    depends_on:
      locations-db:
        condition: service_healthy
    ports:
      - "50051:50051"
  rest-fights:
    image: flyaruu/superheroes-rust-rest-villains:latest
    ports:
      - "8082:8000"
  villains-db:
    image: postgres:16
    ports:
      - "5432"
    environment:
      POSTGRES_USER: superbad
      POSTGRES_PASSWORD: superbad
      POSTGRES_DB: villains_database
    volumes:
      - ./rest-villains/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U superbad -d villains_database"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  heroes-db:
    image: postgres:16
    ports:
      - "5432"
    environment:
      POSTGRES_USER: superman
      POSTGRES_PASSWORD: superman
      POSTGRES_DB: heroes_database
    volumes:
      - ./rest-heroes/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U superman -d heroes_database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  locations-db:
    image: mariadb:11.5
    ports:
      - "3306"
    environment:
      MARIADB_USER: locations
      MARIADB_PASSWORD: locations
      MARIADB_DATABASE: locations_database
      MARIADB_ROOT_PASSWORD: locations
      MARIADB_SKIP_TEST_DB: yes
    volumes:
      - ./grpc-locations/deploy/db-init/initialize-tables.sql:/docker-entrypoint-initdb.d/1-init-tables.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u locations --password=locations"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
