---
name: Superheroes k6 scenario
author: Frank Lyaruu
description: Superheroes (Rust) k6 load testing scenario )
compose-file: !include compose.yml
ignore-unsupported-compose: true
services:
    k6:
      build: k6-image
      environment:
        K6_HOST: http://rest-fights:8000 
      command: ["bash", "-c", "while true; do sleep 3600; done"]
      volumes:
        - ./k6:/k6:ro
        - ./k6/results:/results
flow:
  - name: K6 run 1 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=1 /k6/load.js
        note: Starting k6 Load Test 1 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: K6 run 10 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=10 /k6/load.js
        note: Starting k6 Load Test 10 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: K6 run 50 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=50 /k6/load.js
        note: Starting k6 Load Test 50 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: K6 run 75 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=75 /k6/load.js
        note: Starting k6 Load Test 75 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true             
  - name: K6 run 100 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=100 /k6/load.js
        note: Starting k6 Load Test 100 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: K6 run 200 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=200 /k6/load.js
        note: Starting k6 Load Test 200 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: K6 run 300 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=300 /k6/load.js
        note: Starting k6 Load Test 300 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: K6 run 400 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=400 /k6/load.js
        note: Starting k6 Load Test 400 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: K6 run 500 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=500 /k6/load.js
        note: Starting k6 Load Test 500 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
  - name: K6 run 600 RPS
    container: k6
    commands:
      - type: console
        command: k6 run -e RAMPING_RATE=600 /k6/load.js
        note: Starting k6 Load Test 600 rps
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
