name: Test Docker on GitHub Actions

on:
  pull_request:
  push:
    branches: 
      - main
      - docker-compose-build

jobs:
  cardamon:
    runs-on: ubuntu-latest
    # services:
    #   docker:
    #     image: flyaruu/cardamon_cicd:0.1
    #     options: --privileged --shm-size=2g
    #     volumes:
    #       - /var/run/docker.sock:/var/run/docker.sock:ro
    container:
      image: flyaruu/cardamon_cicd:0.2
      options: --privileged --shm-size=2g
      # volumes:
      #   - /var/run/docker.sock:/var/run/docker.sock:ro
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: grpc-locations
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: rest-heroes
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: rest-villains
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: rest-fights
      - name: Test Docker
        run: |
          pwd
          ls -l
          docker version
          docker info
      - name: Build docker compose
        run: |
          docker compose build
    
      # - name: Pull compose
      #   run: |
      #     docker compose pull

      - name: Cardamon
        run: |
          cardamon run quick
      - name: Log
        run: |
          cat .stderr

  # push_container:
  #   runs-on: ubuntu-latest
  #   services:
  #     docker:
  #       image: docker:dind
  #       options: --privileged --shm-size=2g
  #       volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock:ro
  #   container:
  #     image: ubuntu:latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Install Docker
  #       run: |
  #         apt-get update
  #         apt-get install -y docker.io

  #     - name: Test Docker
  #       run: |
  #         docker version
  #         docker info
